name: student
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.40+59

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^5.0.0+1
  flutter_calendar_carousel: ^1.5.2
  flutter_webview_plugin: any
  gradient_text: ^1.0.2
  percent_indicator: ^3.0.1
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  connectivity: ^3.0.3
  http: ^0.13.1
  intl: ^0.17.0
  another_flushbar: ^1.10.17
  easy_localization: ^3.0.0
  image_picker: ^0.7.2
  camera: ^0.5.8+17
  path: ^1.8.0
  mime: ^1.0.0
  launch_review: ^3.0.1
  liquid_progress_indicator: ^0.3.2
  multi_image_picker: ^4.8.0
  cached_network_image: ^3.0.0
  flutter_swiper: ^1.1.6
  flutter_typeahead: ^3.1.1
  animated_text_kit:  ^4.1.1
  font_awesome_flutter:  ^9.0.0
  url_launcher:  ^6.0.3
  youtube_player_flutter:  ^8.0.0
  image_downloader:  ^0.30.0
  fl_chart: ^0.35.0
  photo_view:  ^0.11.1
  pdf: ^3.2.0
  printing: ^5.3.0
  esys_flutter_share: ^1.0.2
  firebase_messaging: any
  firebase_core: ^1.0.3
  flutter_app_badger: ^1.2.0
  linkwell: ^2.0.6
  open_file: ^3.2.1
  permission_handler: any


dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  path_provider:
  flutter_cached_pdfview:
  sms_autofill :
  pin_input_text_field:

  # firebase_messaging:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/locale/localization_en.json
    - assets/locale/localization_mr.json

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

